[[Librsvg]]
arch = "aarch64"
git-tree-sha1 = "c88db279e5c132dc8f8a612491165efb7530ad0a"
os = "macos"

    [[Librsvg.download]]
    sha256 = "482b9dce438c96256db12381b111a9140283fd01c01928eeb26528abda63c4d2"
    url = "https://github.com/JuliaBinaryWrappers/Librsvg_jll.jl/releases/download/Librsvg-v2.58.5+0/Librsvg.v2.58.5.aarch64-apple-darwin.tar.gz"
[[Librsvg]]
arch = "aarch64"
git-tree-sha1 = "9c167745e41904983cf477066b0c3326c3187f6a"
libc = "glibc"
os = "linux"

    [[Librsvg.download]]
    sha256 = "f652062beb632163a9ae72e8be2a98147565a8f8a2bcce5a2172d59dd249f4c5"
    url = "https://github.com/JuliaBinaryWrappers/Librsvg_jll.jl/releases/download/Librsvg-v2.58.5+0/Librsvg.v2.58.5.aarch64-linux-gnu.tar.gz"
[[Librsvg]]
arch = "aarch64"
git-tree-sha1 = "39c67a474bb9e1d90bd3e8bcccfd087e25e3a8d6"
libc = "musl"
os = "linux"

    [[Librsvg.download]]
    sha256 = "f4a6117ab045d8f04017c118cf022222c1883338065fb32e35d8a0e0dc967063"
    url = "https://github.com/JuliaBinaryWrappers/Librsvg_jll.jl/releases/download/Librsvg-v2.58.5+0/Librsvg.v2.58.5.aarch64-linux-musl.tar.gz"
[[Librsvg]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "34adea8e2ec51330e749a845aa93c4c0b033fd3f"
libc = "glibc"
os = "linux"

    [[Librsvg.download]]
    sha256 = "e99be5adc1aadaa7befbd02fe1b1699ee47de26dfbf887d8fd2296388b277dfb"
    url = "https://github.com/JuliaBinaryWrappers/Librsvg_jll.jl/releases/download/Librsvg-v2.58.5+0/Librsvg.v2.58.5.armv7l-linux-gnueabihf.tar.gz"
[[Librsvg]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ecc49d902cfd7e96c5ea6256eacf5dd41b3238df"
libc = "musl"
os = "linux"

    [[Librsvg.download]]
    sha256 = "ec48cb012b59114159ee41441bd97c11e5f71b8ecd39bfbd2d88a813013628de"
    url = "https://github.com/JuliaBinaryWrappers/Librsvg_jll.jl/releases/download/Librsvg-v2.58.5+0/Librsvg.v2.58.5.armv7l-linux-musleabihf.tar.gz"
[[Librsvg]]
arch = "i686"
git-tree-sha1 = "bd841c5bcac621f322c8d44cd4f21ad4148325a2"
libc = "glibc"
os = "linux"

    [[Librsvg.download]]
    sha256 = "2028c384c86124c2d070b179cadd46bd2f19cad77ac8d980d9727c0ef93c7ca7"
    url = "https://github.com/JuliaBinaryWrappers/Librsvg_jll.jl/releases/download/Librsvg-v2.58.5+0/Librsvg.v2.58.5.i686-linux-gnu.tar.gz"
[[Librsvg]]
arch = "i686"
git-tree-sha1 = "88075672dfb4c9a554db46bab9b889a083bf18ed"
libc = "musl"
os = "linux"

    [[Librsvg.download]]
    sha256 = "75eb6a29a625ce06297f38dd13250554be6f5f315ca727ae297b73f7cd0a34bf"
    url = "https://github.com/JuliaBinaryWrappers/Librsvg_jll.jl/releases/download/Librsvg-v2.58.5+0/Librsvg.v2.58.5.i686-linux-musl.tar.gz"
[[Librsvg]]
arch = "powerpc64le"
git-tree-sha1 = "abb2a1395ad4738e56d8ae67dabeea9aaf5c16cc"
libc = "glibc"
os = "linux"

    [[Librsvg.download]]
    sha256 = "cd9cce2d840c2b105d4028ca77e699964d8c895840e0aa63c50b673d0beae15b"
    url = "https://github.com/JuliaBinaryWrappers/Librsvg_jll.jl/releases/download/Librsvg-v2.58.5+0/Librsvg.v2.58.5.powerpc64le-linux-gnu.tar.gz"
[[Librsvg]]
arch = "x86_64"
git-tree-sha1 = "480f0dbf0958624c4fee21d2559246d7a947889a"
os = "macos"

    [[Librsvg.download]]
    sha256 = "99bed5c42aac0800e44e1b3c94d91100d06c9da57592213d7ba027981acd0905"
    url = "https://github.com/JuliaBinaryWrappers/Librsvg_jll.jl/releases/download/Librsvg-v2.58.5+0/Librsvg.v2.58.5.x86_64-apple-darwin.tar.gz"
[[Librsvg]]
arch = "x86_64"
git-tree-sha1 = "4f3ba29b5b4bb28f63b8fd04731261e30e6858a9"
libc = "glibc"
os = "linux"

    [[Librsvg.download]]
    sha256 = "b72b6484630c6907a1c1f5c15371b214bfbe06666a6a07de6a7134720d1a9890"
    url = "https://github.com/JuliaBinaryWrappers/Librsvg_jll.jl/releases/download/Librsvg-v2.58.5+0/Librsvg.v2.58.5.x86_64-linux-gnu.tar.gz"
[[Librsvg]]
arch = "x86_64"
git-tree-sha1 = "4ab5d2abd8dfec526c2420b52af51c86a954fc6d"
libc = "musl"
os = "linux"

    [[Librsvg.download]]
    sha256 = "052b32b8cca2aeb767126caee8c955eaee0f5157b719f2afae8cd4760f6f9dbb"
    url = "https://github.com/JuliaBinaryWrappers/Librsvg_jll.jl/releases/download/Librsvg-v2.58.5+0/Librsvg.v2.58.5.x86_64-linux-musl.tar.gz"
[[Librsvg]]
arch = "x86_64"
git-tree-sha1 = "18949a23c3ecd0a724b24a512475421a1073b700"
os = "freebsd"

    [[Librsvg.download]]
    sha256 = "f77202c9c3aa80f7ebb06f9c8ec61be368b42650340d5b80ab85b3e4c97b8d85"
    url = "https://github.com/JuliaBinaryWrappers/Librsvg_jll.jl/releases/download/Librsvg-v2.58.5+0/Librsvg.v2.58.5.x86_64-unknown-freebsd.tar.gz"
[[Librsvg]]
arch = "x86_64"
git-tree-sha1 = "a4fc68e8895ecbaf6a8d263c8c4ab2e6326f0ec5"
os = "windows"

    [[Librsvg.download]]
    sha256 = "0194d96e75ee2bae9178804a81a99956c3870ef46b252b780a797b81dd678acf"
    url = "https://github.com/JuliaBinaryWrappers/Librsvg_jll.jl/releases/download/Librsvg-v2.58.5+0/Librsvg.v2.58.5.x86_64-w64-mingw32.tar.gz"
