[[Librsvg]]
arch = "aarch64"
git-tree-sha1 = "b1098e6487d68974e48178ec7373d5ca3aec4aff"
os = "macos"

    [[Librsvg.download]]
    sha256 = "e26ec156d80b602e5eaa1b5fa4ee687686a51aef31493dd246d3af4329091c4a"
    url = "https://github.com/JuliaBinaryWrappers/Librsvg_jll.jl/releases/download/Librsvg-v2.54.5+0/Librsvg.v2.54.5.aarch64-apple-darwin.tar.gz"
[[Librsvg]]
arch = "aarch64"
git-tree-sha1 = "0411c2e82b2d36617cbef90dd95d5c5d6d2f2d36"
libc = "glibc"
os = "linux"

    [[Librsvg.download]]
    sha256 = "7c367c73fd48c5a376e4a2c39354644d1065deb505403bdb0aa6b06efe56a236"
    url = "https://github.com/JuliaBinaryWrappers/Librsvg_jll.jl/releases/download/Librsvg-v2.54.5+0/Librsvg.v2.54.5.aarch64-linux-gnu.tar.gz"
[[Librsvg]]
arch = "aarch64"
git-tree-sha1 = "c2b291fe526980a1e7a755c9d4feb3db031e28c6"
libc = "musl"
os = "linux"

    [[Librsvg.download]]
    sha256 = "352b9a1cec4db5dc4adae1cd156e2a8d6a3a5bab97b760f3bbcf7f1388edc218"
    url = "https://github.com/JuliaBinaryWrappers/Librsvg_jll.jl/releases/download/Librsvg-v2.54.5+0/Librsvg.v2.54.5.aarch64-linux-musl.tar.gz"
[[Librsvg]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c84799cd6475656a7206f5ff3e669289120c8384"
libc = "glibc"
os = "linux"

    [[Librsvg.download]]
    sha256 = "74dafb281bee3739b2a390f81c7ee4f79accfe701c47f723babf550bddbe65d4"
    url = "https://github.com/JuliaBinaryWrappers/Librsvg_jll.jl/releases/download/Librsvg-v2.54.5+0/Librsvg.v2.54.5.armv7l-linux-gnueabihf.tar.gz"
[[Librsvg]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ab306ca41b6263a071a6b29f406fbd84c88a4570"
libc = "musl"
os = "linux"

    [[Librsvg.download]]
    sha256 = "2bfc0c13641528b6ccf22492da755521579b81b5f83b411a299bfd82c439d322"
    url = "https://github.com/JuliaBinaryWrappers/Librsvg_jll.jl/releases/download/Librsvg-v2.54.5+0/Librsvg.v2.54.5.armv7l-linux-musleabihf.tar.gz"
[[Librsvg]]
arch = "i686"
git-tree-sha1 = "95d4423bdea2b5af1c7d258489d47c120556b485"
libc = "glibc"
os = "linux"

    [[Librsvg.download]]
    sha256 = "8320f93389b034110014ff9f7e45a12caa3f251ea20cef12ae1c898e6849fb9b"
    url = "https://github.com/JuliaBinaryWrappers/Librsvg_jll.jl/releases/download/Librsvg-v2.54.5+0/Librsvg.v2.54.5.i686-linux-gnu.tar.gz"
[[Librsvg]]
arch = "i686"
git-tree-sha1 = "440f8f7a248528b5e726a641c4c45f9d5fc35ecc"
libc = "musl"
os = "linux"

    [[Librsvg.download]]
    sha256 = "712377aeb3f07b917e941c5311ab51f3a0b38b182ccf913921f125dac3e94c2c"
    url = "https://github.com/JuliaBinaryWrappers/Librsvg_jll.jl/releases/download/Librsvg-v2.54.5+0/Librsvg.v2.54.5.i686-linux-musl.tar.gz"
[[Librsvg]]
arch = "powerpc64le"
git-tree-sha1 = "b3ca997d758efacc5e4e5b82072b7a6faec440e2"
libc = "glibc"
os = "linux"

    [[Librsvg.download]]
    sha256 = "3051d7d482a15087cceee8b670ae700f870847ac72adef5b53c374f36223c6fe"
    url = "https://github.com/JuliaBinaryWrappers/Librsvg_jll.jl/releases/download/Librsvg-v2.54.5+0/Librsvg.v2.54.5.powerpc64le-linux-gnu.tar.gz"
[[Librsvg]]
arch = "x86_64"
git-tree-sha1 = "ef1e33d68633848e7e4858e8ce2a9c78792d420c"
os = "macos"

    [[Librsvg.download]]
    sha256 = "56e8d2514435576806aee7e9be25b682621dd714f89aa1da3a1a0db69b193bac"
    url = "https://github.com/JuliaBinaryWrappers/Librsvg_jll.jl/releases/download/Librsvg-v2.54.5+0/Librsvg.v2.54.5.x86_64-apple-darwin.tar.gz"
[[Librsvg]]
arch = "x86_64"
git-tree-sha1 = "04123cf3db9b20df4ec72514ae580b2f6cc782b6"
libc = "glibc"
os = "linux"

    [[Librsvg.download]]
    sha256 = "4a02cb4deddb994ddceddd014a0f4f6f28ee91a4847aa42d467322fb41f73d73"
    url = "https://github.com/JuliaBinaryWrappers/Librsvg_jll.jl/releases/download/Librsvg-v2.54.5+0/Librsvg.v2.54.5.x86_64-linux-gnu.tar.gz"
[[Librsvg]]
arch = "x86_64"
git-tree-sha1 = "d179233d639dde4a9e18c45d862672bb7812e467"
libc = "musl"
os = "linux"

    [[Librsvg.download]]
    sha256 = "bd71ee9d60328d159e6474d04a03aaaa3d50a481c5ae27309a2b8acc2bfd1957"
    url = "https://github.com/JuliaBinaryWrappers/Librsvg_jll.jl/releases/download/Librsvg-v2.54.5+0/Librsvg.v2.54.5.x86_64-linux-musl.tar.gz"
[[Librsvg]]
arch = "x86_64"
git-tree-sha1 = "4026d1ac8a6f128f6796dfa22650171314f26426"
os = "freebsd"

    [[Librsvg.download]]
    sha256 = "6965351ccabc1f04efa8b8400b468a7684be9c68fc78485ba4921298ab3b72b6"
    url = "https://github.com/JuliaBinaryWrappers/Librsvg_jll.jl/releases/download/Librsvg-v2.54.5+0/Librsvg.v2.54.5.x86_64-unknown-freebsd.tar.gz"
[[Librsvg]]
arch = "x86_64"
git-tree-sha1 = "5c9c5be2b9f7c41cbc4ed9ec3925b2c854abfac3"
os = "windows"

    [[Librsvg.download]]
    sha256 = "7800cead9e579c67e18ae3413c83262ee0c3ce9560ed46688ffb47bb64ff0d47"
    url = "https://github.com/JuliaBinaryWrappers/Librsvg_jll.jl/releases/download/Librsvg-v2.54.5+0/Librsvg.v2.54.5.x86_64-w64-mingw32.tar.gz"
