# Autogenerated wrapper script for Librsvg_jll for x86_64-w64-mingw32
export libpixbufloader_svg, librsvg, rsvg_convert

using gdk_pixbuf_jll
using Pango_jll
JLLWrappers.@generate_wrapper_header("Librsvg")
JLLWrappers.@declare_file_product(libpixbufloader_svg)
JLLWrappers.@declare_library_product(librsvg, "librsvg-2-2.dll")
JLLWrappers.@declare_executable_product(rsvg_convert)
function __init__()
    JLLWrappers.@generate_init_header(gdk_pixbuf_jll, Pango_jll)
    JLLWrappers.@init_file_product(
        libpixbufloader_svg,
        "lib\\gdk-pixbuf-2.0\\2.10.0\\loaders\\libpixbufloader-svg.dll",
    )

    JLLWrappers.@init_library_product(
        librsvg,
        "bin\\librsvg-2-2.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        rsvg_convert,
        "bin\\rsvg-convert.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
